name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
